# Config file for automatic testing at travis-ci.org
dist: focal
language: python
python:
  - "3.8"
  - "3.9"
install:
  - pip install -r testapp/app/requirements.txt
  - pip install $DJANGO_VERSION --upgrade
env:
  global:
    - DJANGO_VERSION='Django>=3.0'
    - DJANGO_VERSION='Django>=4.0'
    - DJANGO_VERSION='Django>=5.0'
script:
  - cd testapp/app && python manage.py test
  - coverage run --source admin_export_action manage.py test
after_success:
  - codecov -e DJANGO_VERSION
branches:
  only:
    - master
    - debug/tests
sudo: false
