# Generated by Django 3.1.2 on 2020-12-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
        migrations.AddField(
            model_name='news',
            name='datetime',
            field=models.DateTimeField(blank=True, help_text='insert date', null=True, verbose_name='datetime'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.IntegerField(choices=[(0, 'archived'), (1, 'draft'), (2, 'published')], default=1),
        ),
        migrations.AddField(
            model_name='video',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='html is supported', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='please insert a cool title', max_length=50, verbose_name='title'),
        ),
    ]
