# Generated by Django 3.1.2 on 2020-12-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201209_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.IntegerField(choices=[(1, 'generic'), (2, 'specific')], default=1),
        ),
    ]
