# Generated by Django 3.1.4 on 2020-12-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(through='news.NewsTag', to='news.Tag', verbose_name='all tags'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='please insert a cool title', max_length=50, verbose_name='main title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='verbose name'),
        ),
    ]
